name: Node.js CI

on: [push, pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: start server
      run: node server.mjs &
    - name: sleep 3 seconds
      run: sleep 3
    - name: run client
      run: node client.mjs
  
  test-curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: start server
      run: node server.mjs &
    - name: sleep 3 seconds
      run: sleep 3    
    - name: cURL it
      run: curl -v http://127.0.0.1:3399